"""empty message

Revision ID: 49862dfad300
Revises: 134b6ad70b5c
Create Date: 2013-12-06 17:42:55.585513

"""

# revision identifiers, used by Alembic.
revision = '49862dfad300'
down_revision = '134b6ad70b5c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_services',
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('music_service_artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('music_service_name', sa.UnicodeText(), nullable=False),
    sa.Column('_internal_service_id', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['music_service_name'], ['music_services.name'], ),
    sa.PrimaryKeyConstraint('artist_id', 'music_service_name')
    )
    op.create_table('music_service_tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('music_service_name', sa.UnicodeText(), nullable=False),
    sa.Column('_internal_service_id', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['music_service_name'], ['music_services.name'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'music_service_name')
    )
    op.drop_table(u'music_service_users')
    op.drop_column(u'artists', u'services')
    op.add_column(u'grants', sa.Column('_default_scopes', sa.UnicodeText(), nullable=True))
    op.drop_column(u'grants', u'_scopes')
    op.add_column(u'oauth_clients', sa.Column('_redirect_uris', sa.UnicodeText(), nullable=False))
    op.drop_column(u'oauth_clients', u'redirect_uri')
    op.add_column(u'tracks', sa.Column('genre', sa.UnicodeText(), nullable=True))
    op.drop_column(u'tracks', u'services')
    op.drop_column(u'tracks', u'length')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tracks', sa.Column(u'length', sa.INTEGER(), nullable=True))
    op.add_column(u'tracks', sa.Column(u'services', postgresql.ENUM(u'bugs', u'naver-music', name=u'service'), nullable=False))
    op.drop_column(u'tracks', 'genre')
    op.add_column(u'oauth_clients', sa.Column(u'redirect_uri', sa.TEXT(), nullable=False))
    op.drop_column(u'oauth_clients', '_redirect_uris')
    op.add_column(u'grants', sa.Column(u'_scopes', sa.TEXT(), nullable=True))
    op.drop_column(u'grants', '_default_scopes')
    op.add_column(u'artists', sa.Column(u'services', postgresql.ENUM(u'bugs', u'naver-music', name=u'service'), nullable=False))
    op.create_table(u'music_service_users',
    sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'service_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column(u'services', postgresql.ENUM(u'bugs', u'naver-music', name=u'service'), autoincrement=False, nullable=False),
    sa.Column(u'created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'music_service_users_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'user_id', u'service_id', u'services', name=u'music_service_users_pkey')
    )
    op.drop_table('music_service_tracks')
    op.drop_table('music_service_artists')
    op.drop_table('music_services')
    ### end Alembic commands ###
