"""Add init models

Revision ID: 8aae6062293
Revises: None
Create Date: 2013-10-27 23:20:33.352338

"""

# revision identifiers, used by Alembic.
revision = '8aae6062293'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('services', sa.Enum('bugs', 'naver-music', name='service'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('mail', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('services', sa.Enum('bugs', 'naver-music', name='service'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_service_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Unicode(length=255), nullable=False),
    sa.Column('services', sa.Enum('bugs', 'naver-music', name='service'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'service_id', 'services')
    )
    op.create_table('password_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypted_password', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_credentials')
    op.drop_table('music_service_users')
    op.drop_table('credentials')
    op.drop_table('tracks')
    op.drop_table('users')
    op.drop_table('artists')
    ### end Alembic commands ###
